### ISSUE TITLE
发生了错误，[0] RuntimeException in Ueditor.php line 129

### ISSUE THREAD

**Issue by indiboy** [zhangvoice/Ueditor#1]
[0] RuntimeException in Ueditor.php line 129
SplFileInfo::getType(): Lstat failed for /tmp/php2vV3qo

**Comment by zhangvoice** [comment]
@indiboy 这个错误是TP自身错误。笑脸，这个项目暂时不会维护，抱歉。

**Comment by indiboy** [comment]
迟到的回复，这都快一年了，您才回我。
